language: java
jdk:
    - oraclejdk8
addons:
  sonarcloud:
    organization: "ocurr-github" # the key of the org you chose at step #3
    token: SONAR_TOKEN

script:
    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
